### PR TITLE
use shorter sound for sequences

### PR DESCRIPTION
**Pull request by kolewu**
this will be especially useful for scales, but should be configurable.

To make the sound smooth, I fade the cutted part into the next one.

### CODE REVIEW

**Comment by pklinken** [comment]
Thanks for that, did you notice the artifact between each sample ? a little bump of white noise, it would be nice to get that out.

**Comment by kolewu** [comment]
I can't hear anything (despite the noise at the end) and in a simulation of the algorithm there is nothing ugly between the sounds (that is not part of both sourcefiles: the attack is a bit noisy and also is the decay).

I will try to add a mode where the prepared file is saved to the sd-card. Then we are able to directly look at them.

**Comment by pklinken** [comment]
Here is a WAV that has some of the artifacts i mentioned: [http://s000.tinyupload.com/index.php?file_id=91045767313929282627](url)

**Comment by kolewu** [comment]
There is some background noise and maybe that's what you are hearing. This noise looks like denormalization errors from up-/downsampling but usually you cannot hear this so much.  I'll have to look into this.

I just listened carfully to the sound created by the simulation. There is no noise, so I suspect that the android sound system adds the noise.

**Comment by kolewu** [comment]
There is something wrong with your links.  The link above is correct with respect to the text, but the url is pointing to https://github.com/pklinken/Earmouse/pull/url

I often switch between different markup formats and am very grateful about the tiny helper buttons at the top of the edit box. If I press the two rings, I get `[](url)` and then know again what the markup syntax for links is like.

**Comment by kolewu** [comment]
The background noise is there without my change, too.  So I suspect, that the noise added to the attack is what you hear.

**Comment by pklinken** [comment]
Yes the original recordings have a lot of background noise, i think it just overlaps between the samples, i will have a look at the code, though i had hoped to avoid that :p

**Comment by pklinken** [comment]
From Android 6 there is a possibility in the MediaPlayer to speed up recordings while maintaining pitch, that would be an easy solution, unfortunately it isn't available for earlier versions..

**Comment by kolewu** [comment]
Faster is not the solution, because then the sound has the whole decay and the silence at the end.  And since the sounds are not exactly of the same length this sounds a bit uneven.

I have rebased my patch, but there still is this error in the smoothing area. It may be caused by the conversion between `byte` and `short`, because the simulation code doesn't show this _brizzling_ and the conversion is the only difference (that I'm aware of). I will still try to find the error.

**Comment by kolewu** [comment]
I found and fixed the error.  It was caused by sign extension, cause in java all (most?) artihmetic operations are performed with integers and while casting the smaller types the sign is extended.

I will look at a possible implementation with `ByteBuffer`, to make the code more clear and be prepared for other sample formats.

**Pull request merged**
