### PR TITLE
Pull remaining jars from maven repo

### PR DESCRIPTION
**Pull request by krt16s**

### CODE REVIEW

**Comment by kolewu** [comment]
Please use a feature branch for features that should be merged to upstream repo as described in the github guide: [Proposing changes to a project with pull requests](https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/)

Then your own fork could have the same master branch as upstream and you don't have to jump through hoops when your PR has been merged.  And it avoids such ugly branch structure created by merging your contribution: [Fork overview](https://github.com/pklinken/Earmouse/network)

**Comment by pklinken** [comment]
this is me [https://xkcd.com/1597/](url)

**Comment by kolewu** [comment]
:smiley: When you receive a good PR then it is not necessary to do anything in git.  Just click the github Button and then update your local copy.

Sure, it's also possible to do the merge in your local copy:
* add the foreign repository as remote
* checkout out your master
* merge the remote branch
* push the master
* that's all

If i see it right, you can just delete your last commit on your master (the merge from what seems to be a local copy of the remote branch).  The merge is just contained in the commit fb92c3d.

**Comment by pklinken** [comment]
I just wanted to take it to my local branch to test it, next time I'll try to do it the right way :)

**Comment by kolewu** [comment]
There is not a single right way. If you want to test it locally (with or without current changes from master if there are any) just do this:
add the other repository as remote
```
git remote add krt16s https://github.com/krt16s/Earmouse.git
```
go to your current working branch
```
git checkout master
```
create and checkout a new test branch:
```
git checkout -b new-test-branch
```
merge the remote branch
```
git merge krt16s/master
```
Test.

You can even checkout the pull request without detours: [Checking out pull requests locally](https://help.github.com/articles/checking-out-pull-requests-locally/)

**Pull request merged**
